training_site/frontend/urls.py
from django.urls import path

from frontend.views import TestPage, RequestsCheck

app_name = 'frontend'


urlpatterns = [
    path('test-page/', TestPage.as_view(), name='test-page'),
    path('requests-check/', RequestsCheck.as_view(), name='test-page'),
]

training_site/training_site/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

from training_site import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('training_site_app.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('frontend-check/', include('frontend.urls')),
]

if not settings.TESTING:
    urlpatterns.extend(
        debug_toolbar_urls()
    )

training_site/training_site_app/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken import views

from training_site_app.views import (
    CoursesRead,
    CoursesDetailRead,
    CoursesCreatePost,
    CoursesDelete,
    CoursesUpdate,
    ComplexQueryForStudentsSlow,
    ComplexQueryForStudentsOptimized,
    ComplexQueryForCoursesSlow,
    ComplexQueryForCoursesOptimized,
    ComplexQueryForLessonsSlow,
    ComplexQueryForLessonsOptimized,
    Menu,
    Contacts,
    send_email,
    EmailSent,
    CourseViewSet,
    LessonViewSet,
    EducatorViewSet,
    StudentViewSet, UserViewSet, TokenRecreate,
)


app_name = 'training_site_app'

router = DefaultRouter()
router.register('courses', CourseViewSet, 'course')
router.register('lessons', LessonViewSet, 'lesson')
router.register('educators', EducatorViewSet, 'educator')
router.register('students', StudentViewSet, 'student')
router.register('user', UserViewSet, 'user')

urlpatterns = [
    path('', Menu.as_view(), name='menu'),
    path('read/', CoursesRead.as_view(), name='courses_read'),
    path('read/<int:pk>/', CoursesDetailRead.as_view(), name='courses_detail_read'),
    path('create/', CoursesCreatePost.as_view(), name='courses_create'),
    path('update/<int:pk>/', CoursesUpdate.as_view(), name='courses_update'),
    path('delete/<int:pk>/', CoursesDelete.as_view(), name='courses_delete'),
    path('queries/1/slow', ComplexQueryForStudentsSlow.as_view(), name='students_query_1_slow'),
    path('queries/1/optimized', ComplexQueryForStudentsOptimized.as_view(), name='students_query_1_optimized'),
    path('queries/2/slow', ComplexQueryForCoursesSlow.as_view(), name='students_query_2_slow'),
    path('queries/2/optimized', ComplexQueryForCoursesOptimized.as_view(), name='students_query_2_optimized'),
    path('queries/3/slow', ComplexQueryForLessonsSlow.as_view(), name='students_query_3_slow'),
    path('queries/3/optimized', ComplexQueryForLessonsOptimized.as_view(), name='students_query_3_optimized'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('sent_email/', send_email, name='send_email'),
    path('email_sent/', EmailSent.as_view(), name='email_sent'),
    # rest
    path('rest/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token),
    path('token-recreate/', TokenRecreate.as_view(), name='token_recreate')
]

training_site/training_site_app/models.py
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()


class Course(models.Model):
    class Meta:
        ordering = ['pk']

    name = models.CharField(unique=True, max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    class Meta:
        ordering = ['pk']

    number = models.IntegerField()  # course number according to the list
    name = models.CharField(max_length=100)  # title
    video = models.TextField(blank=True, null=False)  # href to video
    text = models.TextField()  # lesson's text
    course = models.ForeignKey(
        to=Course,
        on_delete=models.CASCADE,
        related_name='lessons',
    )  # from which course this lesson

    def __str__(self):
        return self.name


class Educator(models.Model):
    class Meta:
        ordering = ['pk']

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
    )
    teaches_courses = models.ManyToManyField(
        to=Course,
        related_name="teachers",
    )

    def __str__(self):
        return self.user.username


class Student(models.Model):
    class Meta:
        ordering = ['pk']

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
    )
    studying_on_courses = models.ManyToManyField(
        to=Course,
        related_name="students",
    )

    def __str__(self):
        return self.user.username

training_site/training_site_app/forms.py
from django import forms
from .models import Course


class CreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


class UserEmailForm(forms.Form):
    user_email = forms.CharField(label='Enter your email', max_length=100)

training_site/training_site_app/views.py
from time import sleep

from django.contrib.auth import get_user_model
from django.db.models import Count, QuerySet, Q
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from rest_framework import authentication
from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated, DjangoModelPermissions
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet

from training_site_app.forms import CreateForm, UserEmailForm
from training_site_app.models import Course, Lesson, Student, Educator
from training_site_app.serializers import CourseSerializer, LessonSerializer, EducatorSerializer, StudentSerializer, \
    UserSerializer, TokenSerializer
from training_site_app.tasks import send_contact_with_me_email


UserModel = get_user_model()


class Menu(TemplateView):
    template_name = 'training_site_app/menu.html'


class CoursesRead(ListView):
    model = Course
    context_object_name = 'courses'


class CoursesDetailRead(DetailView):
    model = Course
    context_object_name = 'course'


class CoursesCreatePost(CreateView):
    model = Course
    success_url = reverse_lazy('training_site_app:courses_read')
    form_class = CreateForm


class CoursesUpdate(UpdateView):
    model = Course
    fields = ["name", 'description']
    template_name_suffix = "_update_form"
    success_url = reverse_lazy('training_site_app:courses_read')


class CoursesDelete(DeleteView):
    model = Course
    template_name = 'training_site_app/course_confirm_delete.html'
    success_url = reverse_lazy('training_site_app:courses_read')


class ComplexQueryForStudentsSlow(TemplateView):
    # Для каждого студента нужно показать всех преподавателей, которые его обучают(для каждого его курса)
    template_name = 'training_site_app/complex_query_for_students.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # context['users'] = {{
        #     'user': user,
        #     'educators': []
        # }}
        context['users'] = []

        for user in Student.objects.all():
            record = {'user': user}
            courses: list[Course] = user.studying_on_courses.all()
            courses_names: list[str] = [course.name for course in courses]
            record['educators'] = Educator.objects.filter(
                teaches_courses__name__in=courses_names
            )

            context['users'].append(record)

        return context


class ComplexQueryForStudentsOptimized(TemplateView):
    # Для каждого студента нужно показать всех преподавателей, которые его обучают(для каждого его курса)
    template_name = 'training_site_app/complex_query_for_students_optimized.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        records = Student.objects.prefetch_related(
            'user',
            'studying_on_courses__teachers__user'
        ).all()
        context['records'] = list()
        for record in records:
            educators = []
            for course in record.studying_on_courses.all():
                educators += [teacher.user.username for teacher in course.teachers.all()]
            context['records'].append({
                'user': record.user.username,
                'educators': educators,
            })

        return context


class ComplexQueryForCoursesSlow(TemplateView):
    template_name = 'training_site_app/complex_query_for_courses_slow.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        courses: list[Course] = Course.objects.order_by(
            'name'
        ).all()
        context['courses'] = list()

        for course in courses:
            course_data = {
                'name': course.name,
                'students_count': len(course.students.all()),
                'educators_count': len(course.teachers.all()),
                'summary': len(course.students.all()) + len(course.teachers.all()),
            }
            context['courses'].append(course_data)
        return context


class ComplexQueryForCoursesOptimized(TemplateView):
    template_name = 'training_site_app/complex_query_for_courses_slow.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        courses: QuerySet[Course] = Course.objects.prefetch_related(
            'teachers',
            'students',
        ).annotate(
            students_count=Count('students', distinct=True),
            educators_count=Count('teachers', distinct=True),
            summary=(Count('students', distinct=True) + Count('teachers', distinct=True)),
        ).order_by(
            'name'
        ).all()
        context['courses'] = courses

        # for course in courses:
        #     course_data = {
        #         'name': course.name,
        #         'students_count': course.stu,
        #         'educators_count': len(course.students.all()),
        #         'summary': len(course.students.all()) + len(course.teachers.all()),
        #     }
        #     context['courses'].append(course_data)
        return context


class ComplexQueryForLessonsSlow(TemplateView):
    template_name = 'training_site_app/complex_query_for_lessons_slow.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = []

        courses = Course.objects.all()
        for course in courses:
            if course.lessons.count() >= 2 and any(['Введение' in lesson.name for lesson in course.lessons.all()]):
                context['courses'].append({
                    'name': course.name,
                    'students': course.students.all(),
                })

        return context


class ComplexQueryForLessonsOptimized(TemplateView):
    template_name = 'training_site_app/complex_query_for_lessons_slow.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = []

        courses = Course.objects.annotate(
            lessons_count=Count('lessons')
        ).filter(
            Q(lessons__name__icontains='Введение') & Q(lessons_count__gte=2)
        ).prefetch_related(
            'students',
            'students__user'
        ).all()
        for course in courses:
            context['courses'].append({
                'name': course.name,
                'students': course.students.all(),
            })

        return context


class Contacts(TemplateView):
    template_name = 'training_site_app/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserEmailForm

        return context


def send_email(request: HttpRequest):
    form = UserEmailForm(request.POST)
    if form.is_valid():
        user_email = form.cleaned_data['user_email']
        # set into query
        send_contact_with_me_email.delay(user_email)
        return HttpResponseRedirect(reverse_lazy("training_site_app:email_sent"))


class EmailSent(TemplateView):
    template_name = 'training_site_app/email_sent.html'


# Rest api
class CourseViewSet(ModelViewSet):
    queryset = Course.objects.all()
    serializer_class = CourseSerializer
    permission_classes = [DjangoModelPermissions]


class LessonViewSet(ModelViewSet):
    queryset = Lesson.objects.all()
    serializer_class = LessonSerializer
    permission_classes = [DjangoModelPermissions]


class EducatorViewSet(ModelViewSet):
    queryset = Educator.objects.all()
    serializer_class = EducatorSerializer
    permission_classes = [DjangoModelPermissions]


class StudentViewSet(ModelViewSet):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer
    permission_classes = [DjangoModelPermissions]


class UserViewSet(ModelViewSet):
    queryset = UserModel.objects.all()
    serializer_class = UserSerializer
    permission_classes = [DjangoModelPermissions]
    http_method_names = ['get']


class TokenRecreate(APIView):
    def post(self, request):
        old_token = Token.objects.get(user=request.user)
        old_token.delete()
        new_token = Token.objects.create(user=request.user)
        serialized_token = TokenSerializer(instance=new_token)
        return Response(serialized_token.data, status=HTTP_200_OK)

training_site/training_site_app/templates/training_site_app/complex_query_for_courses_optimized.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1>Доступные курсы:</h1>
{% for course in courses %}
<h2>&nbsp;&nbsp;&nbsp;&nbsp;{{course.name}}</h2>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Студентов на курсе: {{ course.students_count }}</h3>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Преподавателей на курсе: {{ course.educators_count }}</h3>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Всего человек на курсе : {{ course.summary }}</h3>
{% endfor %}
{% endblock %}

training_site/training_site_app/templates/training_site_app/complex_query_for_courses_slow.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1>Доступные курсы:</h1>
{% for course in courses %}
<h2>&nbsp;&nbsp;&nbsp;&nbsp;{{course.name}}</h2>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Студентов на курсе: {{ course.students_count }}</h3>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Преподавателей на курсе: {{ course.educators_count }}</h3>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Всего человек на курсе: {{ course.summary }}</h3>
{% endfor %}
{% endblock %}

training_site/training_site_app/templates/training_site_app/complex_query_for_lessons_optimized.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1>Доступные курсы, подходящие под описание:</h1>
{% for course in courses %}
<h2>{{ course.name }}</h2>
{% for student in course.students %}
<h3>&nbsp;&nbsp;&nbsp;&nbsp;- {{ student }}</h3>
{% endfor %}
{% endfor %}
{% endblock %}

training_site/training_site_app/templates/training_site_app/complex_query_for_lessons_slow.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1>Доступные курсы, подходящие под описание:</h1>
{% for course in courses %}
<h2>{{ course.name }}</h2>
{% for student in course.students %}
<h3>&nbsp;&nbsp;&nbsp;&nbsp;- {{ student }}</h3>
{% endfor %}
{% endfor %}
{% endblock %}

training_site/training_site_app/templates/training_site_app/complex_query_for_students.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1>Вот все студенты:</h1>
<h2>---- А вот все их преподаватели со всех их курсов</h2>
<h2>__________________________________________</h2>
{% for record in users %}
<h3>{{ record.user.user.username }}</h3>
{% for educator in record.educators %}
<h5>  ----  {{ educator }}</h5>
{% endfor %}
{% endfor %}
{% endblock %}

training_site/training_site_app/templates/training_site_app/complex_query_for_students_optimized.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1>Вот все студенты:</h1>
<h2>---- А вот все их преподаватели со всех их курсов</h2>
<h2>__________________________________________</h2>
{% for record in records %}
<h3>{{ record.user }}</h3>
{% for educator in record.educators %}
<h5>  ----  {{ educator }}</h5>
{% endfor %}
{% endfor %}
{% endblock %}

training_site/training_site_app/templates/training_site_app/contacts.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<form action="{% url 'training_site_app:send_email' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Contact with me later</button>
</form>
{% endblock %}

training_site/training_site_app/templates/training_site_app/course_confirm_delete.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
  <h1>Подтвердите удаление</h1>
<p>Вы уверены, что хотите удалить "{{ object }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить</button>
    <a href="{% url 'training_site_app:courses_read' %}">Отмена</a>  <!-- Ссылка на страницу со списком объектов -->
</form>
{% endblock %}

training_site/training_site_app/templates/training_site_app/course_detail.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
  <h1>Ingo about current course:</h1>
  <h3>Id: {{ course.id }}</h3>
  <h3>Name: {{ course.name }}</h3>
  <h3>Description: {{ course.description }}</h3>
  <a href="{% url 'training_site_app:courses_delete' pk=course.pk %}"> Удалить</a>
  <a href="{% url 'training_site_app:courses_update' pk=course.pk %}"> Изменить</a>
{% endblock %}

training_site/training_site_app/templates/training_site_app/course_form.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block body %}
  <h1>Создать новый объект</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
</form>
{% endblock %}

training_site/training_site_app/templates/training_site_app/course_list.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block body %}
  <h1>All courses is here:</h1>
  <ul>
    {% for course in courses %}
    <li><a href='{% url "training_site_app:courses_detail_read" pk=course.pk %}'>{{ course.name }}</a></li>
    {% endfor %}
  </ul>
  <a href='{% url "training_site_app:courses_create" %}'>Добавить</a>
{% endblock %}

training_site/training_site_app/templates/training_site_app/course_update_form.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

training_site/training_site_app/templates/training_site_app/email_sent.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1>Email was successfully sent!</h1>
<h3><a href="{% url 'training_site_app:menu' %}">Return to menu</a></h3>
{% endblock %}

training_site/training_site_app/templates/training_site_app/menu.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}
{% block body %}
<h1 style="text-align: center">Menu</h1>
<h2>- First homework (<a href="{% url 'training_site_app:courses_read' %}">CRUD</a> for model)</h2>

<h2>- Second homework (Optimization of queries)</h2>
<h3>&nbsp;&nbsp;&nbsp;&nbsp;Query 1: For each student, display all of his teachers, from all of his courses</h3>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <a href="{% url 'training_site_app:students_query_1_slow' %}">Slow</a></h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <a href="{% url 'training_site_app:students_query_1_optimized' %}">Optimized</a></h4>

<h3>&nbsp;&nbsp;&nbsp;&nbsp;Query 2: For each course you need to calculate the number of: <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. all students,
  <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. all teachers and <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. their total value</h3>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <a href="{% url 'training_site_app:students_query_2_slow' %}">Slow</a></h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <a href="{% url 'training_site_app:students_query_2_optimized' %}">Optimized</a></h4>

<h3>&nbsp;&nbsp;&nbsp;&nbsp;Query 3: For each course, display all students, provided that the number of
  lessons in this course is >= 2, and at least 1 lesson contains “Introduction” in the name (case-sensitive)</h3>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <a href="{% url 'training_site_app:students_query_3_slow' %}">Slow</a></h4>
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- <a href="{% url 'training_site_app:students_query_3_optimized' %}">Optimized</a></h4>

<h2>- Third homework (<a href="{% url 'training_site_app:contacts' %}">RabbitMQ</a>)</h2>
{% endblock %}